import { Metadata } from "next";
import Favicon from "../app/data/icon/icon.png";

export const metadata: Metadata = {
  title: "Animes do Hugo",
  description: "Generated by Next.js",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
