export const metadata = {
  title: "Animes do Hugo",
  description: "Generated by Next.js",
  icons: {
    icon: "app/data/icon.png", // /public path
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
